# Generated by Django 3.2.9 on 2021-12-08 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amigos_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amigo', models.ManyToManyField(to='amigos_app.User1')),
            ],
        ),
    ]
